### ISSUE TITLE
Kipro Ultra: load clip not working

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion-module-aja-kipro#1]
The module is stated to be for the KiPro ultra, but for load clip it uses the command for the old KiPro classic.

It should be /config?action=set&paramid=eParamID_GoToClip&value=clipname.mov
instead of /config?action=set&paramid=eParamID_D1Clip&value=clipname.mov

**Comment by josephdadams** [comment]
I just submitted a PR to fix this.

**Comment by murphytodd4** [comment]
I believe this issue can be closed.
